#### Retrieval from Emails using RAG

1. Load Data from source (Kaggle)
2. Split the Text into Manageable Chunks
3. Create Embeddings and a Vector Store
4.

In [30]:
# ! pip install kaggle
# ! pip install langchain
# ! pip install openai
# ! pip install kaggle
# ! pip install dotenv
# ! pip install pandas
# ! pip install chromadb
# ! pip install sentence_transformers

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Requirement already satisfied: openai in /usr/local/lib/python3.11/dist-packages (1.91.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from openai) (4.9.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.10.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from openai) (2.11.7)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.11/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.11/dist-packages (from openai) (4.14.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.5.0->openai) (3.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (2025.6.15)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.1)

In [2]:
# Download dataset from Kaggle (run this only once to download the data)

"""
import kaggle
from kaggle.api.kaggle_api_extended import KaggleApi
api = KaggleApi()
api.authenticate()
api.dataset_download_files('marawanxmamdouh/email-thread-summary-dataset', path='./data/', unzip=True)
"""

"\nimport kaggle\nfrom kaggle.api.kaggle_api_extended import KaggleApi\napi = KaggleApi()\napi.authenticate()\napi.dataset_download_files('marawanxmamdouh/email-thread-summary-dataset', path='./data/', unzip=True)\n"

In [31]:
# Import all libraries

import pandas as pd
from langchain.text_splitter import RecursiveCharacterTextSplitter  # For splitting large text into smaller chunks
from openai import OpenAI
import os
from dotenv import load_dotenv
import chromadb
from chromadb.utils import embedding_functions
from chromadb.utils.embedding_functions import OpenAIEmbeddingFunction
from sentence_transformers import CrossEncoder, util

In [4]:
# Load local configuration

load_dotenv()
pplx_key = os.getenv('PPLX_API_KEY')
openai_key = os.getenv('OPENAI_API_KEY')
pplx_model=os.getenv('PPLX_BASE_MODEL')
pplx_base_url = os.getenv('PPLX_BASE_URL')
print("Local config loaded")

Local config loaded

In [5]:
# Load data files. These data files are from Kaggle dataset: 
# https://www.kaggle.com/datasets/marawanxmamdouh/email-thread-summary-dataset
email_details = pd.read_csv("/kaggle/input/email-thread-summary-dataset/CSV/email_thread_details.csv")
email_summaries = pd.read_csv("/kaggle/input/email-thread-summary-dataset/CSV/email_thread_summaries.csv")
# email_details = pd.read_csv('data/CSV/email_thread_details.csv')
# email_summaries = pd.read_csv('data/CSV/email_thread_summaries.csv')

In [6]:
# Show sample data

email_details.head()

,thread_id,subject,timestamp,from,to,body
0,1,FW: Master Termination Log,2002-01-29 11:23:42,"Gossett, Jeffrey C. JGOSSET","['Giron', 'Darron C. Dgiron', 'Love', 'Phillip...",\n\n -----Original Message-----\nFrom: =09Ther...
1,1,FW: Master Termination Log,2002-01-31 12:50:00,"Theriot, Kim S. KTHERIO","['Murphy', 'Melissa Mmurphy', 'Gossett', 'Jeff...",\n\n -----Original Message-----\nFrom: =09Panu...
2,1,FW: Master Termination Log,2002-02-05 15:03:35,"Theriot, Kim S. KTHERIO","['Murphy', 'Melissa Mmurphy', 'Anderson', 'Dia...",Note to Stephanie Panus....\n\nStephanie...ple...
3,1,FW: Master Termination Log,2002-02-05 15:06:25,"Theriot, Kim S. KTHERIO","['Hall', 'D. Todd Thall', 'Sweeney', 'Kevin Ks...",\n\n -----Original Message-----\nFrom: =09Panu...
4,1,FW: Master Termination Log,2002-05-28 07:20:35,"Kelly, Katherine L. KKELLY","['Germany', 'Chris Cgerman']",\n\n -----Original Message-----\nFrom: =09McMi...

In [7]:
# Show sample data for email summary

email_summaries.head()

   thread_id                                            summary
0          1  The email thread discusses the Master Terminat...
1          2  A lunch meeting has been scheduled for May 5th...
2          3  Ben is updating a friend on his progress with ...
3          4  The recipient of the email thread initially ex...
4          5  The email thread discusses the long form confi...

In [8]:
email_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21684 entries, 0 to 21683
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   thread_id  21684 non-null  int64
 1   subject    21684 non-null  object
 2   timestamp  21684 non-null  object
 3   from       21684 non-null  object
 4   to         21684 non-null  object
 5   body       21684 non-null  object
dtypes: int64(1), object(5)
memory usage: 1016.6+ KB

In [9]:
email_summaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4167 entries, 0 to 4166
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   thread_id  4167 non-null   int64
 1   summary    4167 non-null   object
dtypes: int64(1), object(1)
memory usage: 65.2+ KB

In [10]:
# Instantiate RecursiveCharacterTextSplitter to create chunks of text

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=30,
)

In [11]:
# sample output of text splitter

print(text_splitter.split_text(email_summaries['summary'][0]))
print(text_splitter.split_text(email_details['body'][0])[1])

["The email thread discusses the Master Termination Log and the need to investigate a CNG LDC (Hope Gas) termination and a $66 million settlement offer. Stephanie Panus sends out the Daily List and Master Termination Log for various dates. Kim Theriot requests her name and Melissa Murphy's name to be removed from the distribution list and adds several names to it. The thread also includes updates on terminations and valid terminations for various companies."]
-----Original Message-----
From: =09Panus, Stephanie =20
Sent:=09Tuesday, January 29, 2002 11:39 AM
To:=09Adams, Laurel; Alonso, Tom; Aronowitz, Alan; Bailey, Susan; Balfour-F=
lanagan, Cyndie; Baughman, Edward; Belden, Tim; Bishop, Serena; Brackett, D=
ebbie R.; Bradford, William S.; Browning, Mary Nell; Bruce, James; Bruce, M=
ichelle; Bruce, Robert; Buerkle, Jim; Calger, Christopher F.; Carrington, C=
lara; Considine, Keith; Cordova, Karen A.; Crandall, Sean; Cutsforth, Diane=
; Diamond, Russell; Dunton, Heather; Edison, Susan; Elafandi, Mo; Fischer, =
Mark; Flores, Nony; Fondren, Mark; Gorny, Vladimir; Gorte, David; Gresham, =
Wayne; Hagelmann, Bjorn; Hall, Steve C. (Legal); Harkness, Cynthia; Hendry,=
 Brent; Johnston, Greg; Keohane, Peter; Lindeman, Cheryl; Little, Kelli; Ma=
llory, Chris; Mann, Kay; Mcginnis, Stephanie; McGrory, Robert; McMichael Jr=
., Ed; Miller, Don (Asset Mktg); Moore, Janet H.; Moran, Tom; Murphy, Harla=

In [12]:
# Merge emails per thread_id by concatenating email_texts in order

grouped = email_details.groupby("thread_id")["body"].apply(lambda x: "\n\n".join(x)).reset_index()

In [13]:
grouped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4167 entries, 0 to 4166
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   thread_id  4167 non-null   int64
 1   body       4167 non-null   object
dtypes: int64(1), object(1)
memory usage: 65.2+ KB

In [14]:
# Create chunks for the email bodies and summaries

docs, ids, metas = [], [], []

for i, row in grouped.iterrows():
    thid = str(row['thread_id'])
    text = str(row['body'])
    for k, ch in enumerate(text_splitter.split_text(text)):
        docs.append(ch)
        ids.append(f"{thid}::chunk::{k}")
        metas.append(
            {
                "thread_id": thid,
                "source" : "email_details",
                "chunk_index" : k
            }
        )

for i, row in email_summaries.iterrows():
    thid = str(row['thread_id'])
    text = str(row['summary'])
    docs.append(text)
    ids.append(f"{thid}::summary")
    metas.append(
        {
            "thread_id": thid,
            "source" : "email_summaries"
        }
    )

In [15]:
# client.delete_collection("email_collection")

In [16]:
# Call PersistentClient()
persist_dir = "./chroma_emails"
client = chromadb.PersistentClient(path=persist_dir)

# create embedding function using SentenceTransformer
embed = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L6-v2")

# create embedding function using OpenAI
# embed = OpenAIEmbeddingFunction(api_key=openai_key,model_name="text-embedding-ada-002")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [17]:
# create or get the collection
collection = client.get_or_create_collection(
    name="email_collection",
    embedding_function=embed
)

In [18]:
# collection.add(documents=docs, ids=ids, metadatas=metas)

In [19]:
def batch_add(collection, documents, ids, metadatas, batch_size=5000):
    for i in range(0, len(documents), batch_size):
        batch_docs = documents[i:i+batch_size]
        batch_ids = ids[i:i+batch_size]
        batch_metas = metadatas[i:i+batch_size]
        collection.add(documents=batch_docs, ids=batch_ids, metadatas=batch_metas)

In [20]:
collection.peek()

{'ids': [],
 'embeddings': array([], dtype=float64),
 'documents': [],
 'uris': None,
 'included': ['metadatas', 'documents', 'embeddings'],
 'data': None,
 'metadatas': []}

In [21]:
batch_add(collection, docs, ids, metas)

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

Batches:   0%|          | 0/157 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [22]:
print(f"Stored {len(docs)} chunks of email threads to ChromaDB")

Stored 50003 chunks of email threads to ChromaDB

In [25]:
# define a function to get response from the database for user query

def get_query_results(input_query):

    results = collection.query(
    query_texts=input_query,
    n_results=10
    )

    # Create a dataframe of the results
    results_df = pd.DataFrame(
        {
            'Metadatas': results['metadatas'][0], 
            'Documents': results['documents'][0], 
            'Distances': results['distances'][0], 
            "IDs":results["ids"][0]
        }
    )
    
    # Initialise the cross encoder model for re-ranking of results    
    cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')
    cross_inputs = [[input_query, response] for response in results_df['Documents']]
    cross_rerank_scores = cross_encoder.predict(cross_inputs)

    # merge the re-ranked scores
    results_df['Reranked_scores'] = cross_rerank_scores
    
    # top 3 results basis reranked scores
    top_3_rerank = results_df.sort_values(by='Reranked_scores', ascending=False)
    top_3_RAG = top_3_rerank[["Documents", "Metadatas"]][:3]
    
    return top_3_RAG

In [28]:
get_query_results("ISDA contract")

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

,Documents,Metadatas
5,"To: Steven.Vu@enron.com, Catherine.Woolgar@enr...","{'source': 'email_details', 'chunk_index': 5, ..."
2,"Dear Steven:\n\nSince this last e.mail below, ...","{'chunk_index': 3, 'thread_id': '2212', 'sourc..."
3,"Dear Steven:\n\nSince this last e.mail below, ...","{'chunk_index': 10, 'thread_id': '2212', 'sour..."

**Retrieval Augmented Generation**

In [70]:
# Define a function to generate response.
# Provide comprehensive prompt

from openai import OpenAI
PPLX_API_KEY="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"
PPLX_BASE_URL="https://api.perplexity.ai"
PPLX_BASE_MODEL="sonar-pro"

client = OpenAI(api_key = PPLX_API_KEY, base_url = PPLX_BASE_URL)

def generate_response(user_query):

    # get query response
    query_response = get_query_results(user_query)

    # define a system message prompt
    system_message = f"""
    You are a helpful assistance that helps organisation find and validate past decisions, 
    stratagies, and data by scanning the huge corpus of email threads.
    """

    # define a user message prompt
    user_prompt = f"""
    You are helpful assistance who can effectively look at historical email chains, email threads,
    and email conversations. You have a question asked by the user in '{user_query}' and you have 
    query results from the email corpus in dataframe {query_response}.
    
    These results are text from the email threads relevant to the user query.
    The column 'document' in the dataframe contains the actual text from the email thread.
    The column 'metadata' has its corresponding thread details.

    Use the documents in '{query_response}' to answer the query '{user_query}'.

    Here are some guidelines for performing this task:
    1. Try to provide accurate information
    2. The email threads may have redundant information. Choose only relevant information for the query
    3. If you can't provide the complete answer, provide any other information that may be helpful for the user to refer.
    4. You are a customer facing assistance, so no need to provide any internal working and additional information.
    5. Just limit your resposne to the query.

    The generated response should answer the query directly addressing the user and avoiding additional information. 
    If you think that the query is not relevant to the document, reply that the query is irrelevant. 
    Provide the final response as a well-formatted and easily readable text along with the citation. 
    Provide your complete response first with all information, and then provide the citations.
    """
    messages = [
        {"role" : "system", "content" : system_message},
        {"role" : "user", "content" : user_prompt}
    ]

    llm_response = client.chat.completions.create(
        # model = "gpt-3.5-turbo",
        model = PPLX_BASE_MODEL,
        messages = messages
    )

    final_response_content = llm_response.choices[0].message.content.split('\n')
    print("*"*100)
    print(f"User Query: {user_query}")
    print("*"*100)
    
    print("\n"*3)
    
    print("*"*100)
    print(f"Top 3 results from the search layer")
    print("*"*100)
    print(query_response)
    print("="*100)
    
    print("\n"*3)

    print("*"*100)
    print(f"Final output generated by the LLM")
    print("*"*100)
    print(f"{final_response_content}")
    print("="*100)
    
    # return llm_response.choices[0].message.content.split('\n')

In [71]:
# Query 1

generate_response("ISDA contract details")

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

****************************************************************************************************
User Query: ISDA contract details
****************************************************************************************************




****************************************************************************************************
Top 3 results from the search layer
****************************************************************************************************
                                           Documents  \
8  Credit.com is requesting a list of all counter...
7  Tana - can you please give me an update on whe...
0  Steven Curlee@ENRON\n\t09/28/2000 09:29 AM\n\t...

                                           Metadatas
8  {'source': 'email_summaries', 'thread_id': '11...
7  {'chunk_index': 14, 'source': 'email_details',...
0  {'source': 'email_details', 'thread_id': '926'...
====================================================================================================




****************************************************************************************************
Final output generated by the LLM
****************************************************************************************************
['Here are the details regarding an **ISDA contract**, based on the relevant email threads:', '', '- The ISDA contract, formally known as the **ISDA Master Agreement**, is a legal document that governs derivative transactions between counterparties.', '- **Credit.com is requesting a list of all counterparties that have an ISDA agreement with ENRON, including their respective ISDA contract details**. This indicates that ENRON maintains records of counterparties with whom they have active ISDA contracts, and these can be referenced or provided as needed.', '- There are ongoing **internal updates** and communications related to ISDA agreements (example: a request for an update on whether a certain ISDA contract is signed by both parties). This means that contract status and counterparties are tracked through coordinated internal communication chains.', '', 'From the extracted email content:', '- You can request a **list of counterparties with ISDA agreements** from ENRON’s records.', '- For specific contract details (terms, signatory status, amendments, collateral arrangements), internal communications may provide updates but will typically be available from the legal/contracts or risk management team.', '- If you need a particular counterparty’s ISDA contract details or status, these are maintained and can be furnished upon request.', '', '**Citations:**  ', ' Credit.com is requesting a list of all counterparties that have an ISDA agreement with ENRON, including their respective ISDA contract details.  ', ' Tana - can you please give me an update on whether a certain ISDA contract is signed by both parties, suggesting ongoing tracking and updates of ISDA contract statuses.']
====================================================================================================

In [ ]:
# Query 2

generate_response("ISDA contract details")

In [ ]:
# Query 3

generate_response("ISDA contract details")