#### Retrieval from Emails using RAG

1. Load Data from source (Kaggle)
2. Split the Text into Manageable Chunks
3. Create Embeddings and a Vector DB (Chroma DB)
4. Create a query response layer (R)
5. Create Prompt for LLM (A)
6. Generate response from LLM (G)

In [ ]:
# ! pip install kaggle
# ! pip install langchain
# ! pip install openai
# ! pip install kaggle
! pip install dotenv
# ! pip install pandas
! pip install chromadb
# ! pip install sentence_transformers
! pip install protobuf==3.20.0

In [ ]:
# Download dataset from Kaggle (run this only once to download the data)


import kaggle
from kaggle.api.kaggle_api_extended import KaggleApi
api = KaggleApi()
api.authenticate()
api.dataset_download_files('marawanxmamdouh/email-thread-summary-dataset', path='./data/', unzip=True)

In [1]:
# Import all libraries

import pandas as pd
from langchain.text_splitter import RecursiveCharacterTextSplitter  # For splitting large text into smaller chunks
from openai import OpenAI
import os
from dotenv import load_dotenv
import chromadb
from chromadb.utils import embedding_functions
from chromadb.utils.embedding_functions import OpenAIEmbeddingFunction
from sentence_transformers import CrossEncoder, util

In [45]:
env = "kaggle"
try:
  from google.colab import userdata
  pplx_key = userdata.get('PREPLEXITY_API_KEY')
  openai_key = userdata.get('OPENAI_KEY')
  pplx_model="sonar-pro"
  pplx_base_url = "https://api.perplexity.ai/"
  env="colab"
  print("Google Secret config loaded")
except:
  # Load local configuration
  load_dotenv()
  from google.colab import userdata
  pplx_key = os.getenv('PPLX_API_KEY')
  openai_key = os.getenv('OPENAI_API_KEY')
  pplx_model=os.getenv('PPLX_BASE_MODEL')
  pplx_base_url = os.getenv('PPLX_BASE_URL')
  env="local"
  print("Local config loaded")

Google Secret config loaded

In [10]:
# Load data files. These data files are from Kaggle dataset:
# https://www.kaggle.com/datasets/marawanxmamdouh/email-thread-summary-dataset
if env == "kaggle":
  email_details_file = "/kaggle/input/email-thread-summary-dataset/CSV/email_thread_details.csv"
  email_summary_file = "/kaggle/input/email-thread-summary-dataset/CSV/email_thread_summaries.csv"
elif env == "local":
  email_details = pd.read_csv('data/CSV/email_thread_details.csv')
  email_summaries = pd.read_csv('data/CSV/email_thread_summaries.csv')
elif env == "colab":
  email_details_file = "/content/data/CSV/email_thread_details.csv"
  email_summary_file = "/content/data/CSV/email_thread_summaries.csv"

email_details = pd.read_csv(email_details_file)
email_summaries = pd.read_csv(email_summary_file)

In [11]:
# Show sample data

email_details.head()

,thread_id,subject,timestamp,from,to,body
0,1,FW: Master Termination Log,2002-01-29 11:23:42,"Gossett, Jeffrey C. JGOSSET","['Giron', 'Darron C. Dgiron', 'Love', 'Phillip...",\n\n -----Original Message-----\nFrom: =09Ther...
1,1,FW: Master Termination Log,2002-01-31 12:50:00,"Theriot, Kim S. KTHERIO","['Murphy', 'Melissa Mmurphy', 'Gossett', 'Jeff...",\n\n -----Original Message-----\nFrom: =09Panu...
2,1,FW: Master Termination Log,2002-02-05 15:03:35,"Theriot, Kim S. KTHERIO","['Murphy', 'Melissa Mmurphy', 'Anderson', 'Dia...",Note to Stephanie Panus....\n\nStephanie...ple...
3,1,FW: Master Termination Log,2002-02-05 15:06:25,"Theriot, Kim S. KTHERIO","['Hall', 'D. Todd Thall', 'Sweeney', 'Kevin Ks...",\n\n -----Original Message-----\nFrom: =09Panu...
4,1,FW: Master Termination Log,2002-05-28 07:20:35,"Kelly, Katherine L. KKELLY","['Germany', 'Chris Cgerman']",\n\n -----Original Message-----\nFrom: =09McMi...

In [12]:
# Show sample data for email summary

email_summaries.head()

   thread_id                                            summary
0          1  The email thread discusses the Master Terminat...
1          2  A lunch meeting has been scheduled for May 5th...
2          3  Ben is updating a friend on his progress with ...
3          4  The recipient of the email thread initially ex...
4          5  The email thread discusses the long form confi...

In [13]:
email_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21684 entries, 0 to 21683
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   thread_id  21684 non-null  int64
 1   subject    21684 non-null  object
 2   timestamp  21684 non-null  object
 3   from       21684 non-null  object
 4   to         21684 non-null  object
 5   body       21684 non-null  object
dtypes: int64(1), object(5)
memory usage: 1016.6+ KB

In [14]:
email_summaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4167 entries, 0 to 4166
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   thread_id  4167 non-null   int64
 1   summary    4167 non-null   object
dtypes: int64(1), object(1)
memory usage: 65.2+ KB

In [16]:
# Instantiate RecursiveCharacterTextSplitter to create chunks of text

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=30,
)

In [17]:
# sample output of text splitter

print(text_splitter.split_text(email_summaries['summary'][0]))
print(text_splitter.split_text(email_details['body'][0])[1])

["The email thread discusses the Master Termination Log and the need to investigate a CNG LDC (Hope Gas) termination and a $66 million settlement offer. Stephanie Panus sends out the Daily List and Master Termination Log for various dates. Kim Theriot requests her name and Melissa Murphy's name to be removed from the distribution list and adds several names to it. The thread also includes updates on terminations and valid terminations for various companies."]
-----Original Message-----
From: =09Panus, Stephanie =20
Sent:=09Tuesday, January 29, 2002 11:39 AM
To:=09Adams, Laurel; Alonso, Tom; Aronowitz, Alan; Bailey, Susan; Balfour-F=
lanagan, Cyndie; Baughman, Edward; Belden, Tim; Bishop, Serena; Brackett, D=
ebbie R.; Bradford, William S.; Browning, Mary Nell; Bruce, James; Bruce, M=
ichelle; Bruce, Robert; Buerkle, Jim; Calger, Christopher F.; Carrington, C=
lara; Considine, Keith; Cordova, Karen A.; Crandall, Sean; Cutsforth, Diane=
; Diamond, Russell; Dunton, Heather; Edison, Susan; Elafandi, Mo; Fischer, =
Mark; Flores, Nony; Fondren, Mark; Gorny, Vladimir; Gorte, David; Gresham, =
Wayne; Hagelmann, Bjorn; Hall, Steve C. (Legal); Harkness, Cynthia; Hendry,=
 Brent; Johnston, Greg; Keohane, Peter; Lindeman, Cheryl; Little, Kelli; Ma=
llory, Chris; Mann, Kay; Mcginnis, Stephanie; McGrory, Robert; McMichael Jr=
., Ed; Miller, Don (Asset Mktg); Moore, Janet H.; Moran, Tom; Murphy, Harla=

In [18]:
# Merge emails per thread_id by concatenating email_texts in order

grouped = email_details.groupby("thread_id")["body"].apply(lambda x: "\n\n".join(x)).reset_index()

In [19]:
grouped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4167 entries, 0 to 4166
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   thread_id  4167 non-null   int64
 1   body       4167 non-null   object
dtypes: int64(1), object(1)
memory usage: 65.2+ KB

In [20]:
# Create chunks for the email bodies and summaries

docs, ids, metas = [], [], []

for i, row in grouped.iterrows():
    thid = str(row['thread_id'])
    text = str(row['body'])
    for k, ch in enumerate(text_splitter.split_text(text)):
        docs.append(ch)
        ids.append(f"{thid}::chunk::{k}")
        metas.append(
            {
                "thread_id": thid,
                "source" : "email_details",
                "chunk_index" : k
            }
        )

for i, row in email_summaries.iterrows():
    thid = str(row['thread_id'])
    text = str(row['summary'])
    docs.append(text)
    ids.append(f"{thid}::summary")
    metas.append(
        {
            "thread_id": thid,
            "source" : "email_summaries"
        }
    )

In [ ]:
# client.delete_collection("email_collection")

In [22]:
import torch
print(torch.cuda.get_device_name(0))  # Prints the name of the GPU
print(torch.cuda.device_count())     # Number of GPUs available
print(torch.cuda.current_device())   # Current GPU being used

Tesla T4
1
0

In [23]:
# Call PersistentClient()
persist_dir = "./chroma_emails"
client = chromadb.PersistentClient(path=persist_dir)

# create embedding function using SentenceTransformer
embed = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L6-v2", device="cuda")

# create embedding function using OpenAI
# embed = OpenAIEmbeddingFunction(api_key=openai_key,model_name="text-embedding-ada-002")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [24]:
# create or get the collection
collection = client.get_or_create_collection(
    name="email_collection",
    embedding_function=embed
)

In [ ]:
# collection.add(documents=docs, ids=ids, metadatas=metas)

In [35]:
import tqdm
def batch_add(collection, documents, ids, metadatas, batch_size=5000):
    for i in tqdm.tqdm(range(0, len(documents), batch_size)):
        batch_docs = documents[i:i+batch_size]
        batch_ids = ids[i:i+batch_size]
        batch_metas = metadatas[i:i+batch_size]
        collection.add(documents=batch_docs, ids=batch_ids, metadatas=batch_metas)

In [36]:
batch_add(collection, docs, ids, metas)

100%|██████████| 11/11 [03:00<00:00, 16.38s/it]

In [37]:
print(f"Stored {len(docs)} chunks of email threads to ChromaDB")

Stored 50003 chunks of email threads to ChromaDB

In [46]:
# define a function to get response from the database for user query

def get_query_results(input_query):

    results = collection.query(
    query_texts=input_query,
    n_results=10
    )

    # Create a dataframe of the results
    results_df = pd.DataFrame(
        {
            'Metadatas': results['metadatas'][0],
            'Documents': results['documents'][0],
            'Distances': results['distances'][0],
            "IDs":results["ids"][0]
        }
    )

    # Initialise the cross encoder model for re-ranking of results
    cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')
    cross_inputs = [[input_query, response] for response in results_df['Documents']]
    cross_rerank_scores = cross_encoder.predict(cross_inputs)

    # merge the re-ranked scores
    results_df['Reranked_scores'] = cross_rerank_scores

    # top 3 results basis reranked scores
    top_3_rerank = results_df.sort_values(by='Reranked_scores', ascending=False)
    top_3_RAG = top_3_rerank[["Documents", "Metadatas"]][:3]

    return top_3_RAG

In [39]:
get_query_results("ISDA contract")

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

,Documents,Metadatas
5,"To: Steven.Vu@enron.com, Catherine.Woolgar@enr...","{'source': 'email_details', 'thread_id': '3682..."
2,"Dear Steven:\n\nSince this last e.mail below, ...","{'source': 'email_details', 'thread_id': '3682..."
3,"Dear Steven:\n\nSince this last e.mail below, ...","{'source': 'email_details', 'chunk_index': 3, ..."

**Retrieval Augmented Generation**

In [67]:
# Define a function to generate response.
# Provide comprehensive prompt

from openai import OpenAI

client = OpenAI(api_key = pplx_key, base_url = pplx_base_url)

def generate_response(user_query):

    # get query response
    query_response = get_query_results(user_query)

    # define a system message prompt
    system_message = f"""
    You are a helpful assistance that helps organisation find and validate past decisions,
    stratagies, and data by scanning the huge corpus of email threads.
    """

    # define a user message prompt
    user_prompt = f"""
    You are helpful assistance who can effectively look at historical email chains, email threads,
    and email conversations. You have a question asked by the user in '{user_query}' and you have
    query results from the email corpus in dataframe {query_response}.

    These results are text from the email threads relevant to the user query.
    The column 'document' in the dataframe contains the actual text from the email thread.
    The column 'metadata' has its corresponding thread details.

    Use the documents in '{query_response}' to answer the query '{user_query}'.

    Here are some guidelines for performing this task:
    1. Try to provide accurate information
    2. The email threads may have redundant information. Choose only relevant information for the query
    3. If you can't provide the complete answer, provide any other information that may be helpful for the user to refer.
    4. You are a customer facing assistance, so no need to provide any internal working and additional information.
    5. Just limit your resposne to the query.

    The generated response should answer the query directly addressing the user and avoiding additional information.
    If you think that the query is not relevant to the document, reply that the query is irrelevant.
    Provide the final response as a well-formatted and easily readable text along with the citation.
    Provide your complete response first with all information, and then provide the citations.
    """
    messages = [
        {"role" : "system", "content" : system_message},
        {"role" : "user", "content" : user_prompt}
    ]

    llm_response = client.chat.completions.create(
        # model = "gpt-3.5-turbo",
        model = pplx_model,
        messages = messages
    )

    final_response_content = llm_response.choices[0].message.content.split('\n')
    return user_query, query_response, final_response_content

In [79]:
import textwrap

def print_final_output(user_query, query_response, final_response_content):

    print("*"*100)
    print(f"User Query: {user_query}")
    print("*"*100)

    print("\n"*1)

    print("*"*100)
    print(f"Top 3 results from the search layer")
    print("*"*100)
    print(query_response)
    print("="*100)

    print("\n"*2)

    print("*"*100)
    print(f"Final output generated by the LLM")
    print("*"*100)
    # Wrap the output text
    wrapped_response = "\n".join(["\n".join(textwrap.wrap(line, width=100)) for line in final_response_content])
    print(f"{wrapped_response}")
    print("="*100)

In [80]:
# Query 1

user_query, query_response, final_response_content = generate_response("who approved the photoshoot for the newsletter")

print_final_output(user_query, query_response, final_response_content)

****************************************************************************************************
User Query: who approved the photoshoot for the newsletter
****************************************************************************************************


****************************************************************************************************
Top 3 results from the search layer
****************************************************************************************************
                                           Documents  \
2  The email thread revolves around a forwarded e...
4  The email thread begins with a discussion abou...
9  Jassem,\n\nAttached is the latest update for t...

                                           Metadatas
2  {'thread_id': '2772', 'source': 'email_summari...
4  {'thread_id': '756', 'source': 'email_summaries'}
9  {'chunk_index': 0, 'source': 'email_details', ...
====================================================================================================



****************************************************************************************************
Final output generated by the LLM
****************************************************************************************************
The photoshoot for the newsletter was approved by Jassem, as indicated by the email text:
"Jassem,\n\nAttached is the latest update for the newsletter photoshoot, as per your approval".

**Citation:**
 Jassem,\n\nAttached is the latest update for the newsletter photoshoot, as per your approval
====================================================================================================

In [81]:
# Query 2

user_query, query_response, final_response_content = generate_response("how much fine was required to be paid in T-6 leak")

print_final_output(user_query, query_response, final_response_content)

****************************************************************************************************
User Query: how much fine was required to be paid in T-6 leak
****************************************************************************************************


****************************************************************************************************
Top 3 results from the search layer
****************************************************************************************************
                                           Documents  \
5  We do not have to pay the $1.2 Million for the...
9  $30 million bucks!!!  I would have hoped for 1...
7  Dan Rittgers\n\n -----Original Message-----\nF...

                                           Metadatas
5  {'thread_id': '2801', 'chunk_index': 5, 'sourc...
9  {'chunk_index': 1, 'thread_id': '295', 'source...
7  {'chunk_index': 6, 'source': 'email_details', ...
====================================================================================================



****************************************************************************************************
Final output generated by the LLM
****************************************************************************************************
The fine required to be paid for the T-6 leak was **$30 million**[1].

**Citations:**
 "$30 million bucks!!! I would have hoped for 1..."
[1] "The company has agreed to pay over $30 million in criminal fines and civil penalties..."
====================================================================================================

In [82]:
# Query 3

user_query, query_response, final_response_content = generate_response("search for any emails related to harrassment of people")

print_final_output(user_query, query_response, final_response_content)

****************************************************************************************************
User Query: search for any emails related to harrassment of people
****************************************************************************************************


****************************************************************************************************
Top 3 results from the search layer
****************************************************************************************************
                                           Documents  \
5  The email thread includes various topics. The ...
7  The email thread consists of multiple unrelate...
0  The email thread consists of three emails. The...

                                           Metadatas
5  {'source': 'email_summaries', 'thread_id': '119'}
7  {'thread_id': '198', 'source': 'email_summaries'}
0  {'thread_id': '3498', 'source': 'email_summari...
====================================================================================================



****************************************************************************************************
Final output generated by the LLM
****************************************************************************************************
There are no emails found in the provided threads that relate to the harassment of people. The
information in these email summaries does not discuss or mention harassment.

Citations:
[5], ,
====================================================================================================